services:

  database: 
    container_name: DatabaseAluMind
    image: postgres:latest
    env_file:
      - ".env"
    environment:
      - POSTGRES_DB=${DATABASE__DB_DATABASE}
      - POSTGRES_USER=${DATABASE__DB_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE__DB_PASSWORD}
    volumes:
      - DatabaseAluMind:/var/lib/postgresql/data
    ports:
      - "${DATABASE__DB_PORT}:5432"

volumes:
  DatabaseAluMind: